CREATE SCHEMA MERCADO_ALENCAR;

CREATE TABLE IF NOT EXISTS MERCADO_ALENCAR.CLIENTE(
    ID SERIAL,
    NOME VARCHAR(100),
    TELEFONE VARCHAR(20)
);

CREATE TABLE MERCADO_ALENCAR.VENDA(
    ID SERIAL,
    CLIENTE NUMERIC,
    LOGRADOURO VARCHAR(200),
    NUMERO VARCHAR(15),
    COMPLEMENTO VARCHAR(500),
    BAIRRO VARCHAR(100),
    OBS VARCHAR(100),
    PAGO BOOLEAN DEFAULT FALSE,
    LEVAR_TROCO BOOLEAN DEFAULT FALSE,
    TROCO VARCHAR(6),
    CARTAO BOOLEAN DEFAULT FALSE
    );
